dist: xenial

language: python

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

env:
  - DJANGO="Django>=3.0,<3.1"
  - DJANGO="Django>=2.2,<2.3"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.7,<1.8"

install:
  - pip install -U coverage coveralls $DJANGO

script:
  - coverage run --source=siteblocks setup.py test

matrix:

  exclude:

   - python: 3.8
     env: DJANGO="Django>=1.10,<1.11"

   - python: 3.8
     env: DJANGO="Django>=1.9,<1.10"

   - python: 3.8
     env: DJANGO="Django>=1.8,<1.9"

   - python: 3.7
     env: DJANGO="Django>=1.7,<1.8"

   - python: 3.6
     env: DJANGO="Django>=1.7,<1.8"

   - python: 3.5
     env: DJANGO="Django>=3.0,<3.1"

   - python: 3.5
     env: DJANGO="Django>=1.7,<1.8"


after_success:
  coveralls
